# Generated by Django 4.1.2 on 2022-10-28 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('iin', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(blank=True, default=None, max_length=14)),
                ('emergency_phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_details', models.CharField(max_length=200)),
                ('is_married', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Dermatologists', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('iin', models.CharField(max_length=12)),
                ('experience', models.IntegerField()),
                ('category', models.CharField(choices=[('Highest', 'Highest'), ('First', 'First'), ('Second', 'Second')], default='First', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('schedule_details', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('PhD', 'PhD'), ('MD', 'MD'), ('Bachelor', 'Bachelor')], default='Bachelor', max_length=15)),
                ('rating', models.PositiveIntegerField()),
                ('homepage_url', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
